services:
  robotic_arm_mec:
    build:
      context: ./ros/
      dockerfile: Dockerfile
    container_name: robotic_arm_mec
    network_mode: host  # Use host network for easier X11 and discovery
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=13
      - LAUNCH_PACKAGE=modular_gateway_sender
      - LAUNCH_FILE=robotic_arm_mec_launch.py
      - OPERATION_MODE=p2p
      - DISPLAY=${DISPLAY}  # Pass host display to container
      - TELEOP=${TELEOP:-false}
      - IK_MEC=${IK_MEC:-false}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
      - ./ros/src/ros_ws/launch:/home/ubuntu/ros_ws/launch
      - ./ros/src/ros_ws/roarm_control:/home/ubuntu/ros_ws/roarm_control
      - ./cpplib:/home/ubuntu/cpplib_src
      - ./external_repos/RoArm-M1:/home/ubuntu/ros_ws/src/RoArm-M1  # Mount RoArm-M1 into src
    privileged: true
    tty: true
    command: >
      /bin/bash -c "
      chmod +x /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh &&
      source /opt/ros/jazzy/setup.bash &&
      bash /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh teleop:=$$TELEOP IK_MEC:=$$IK_MEC
      "
