services:
  ros2:
    build:
      context: ./ros/
      dockerfile: Dockerfile  # nebo použijte vlastní Dockerfile, pokud chcete specifikovat vlastní image
    # user: "1000:1000"  # Použití UID a GID z hostitele
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=12
      # - DEVICE=$(readlink -f /dev/teensy)
    # user: "${UID}:${GID}"
    # run this before docker compose run/up
    # export UID=$(id -u)
    # export GID=$(id -g)
    # chown -R pepa:admin /home/pepa/dokumenty
    #devices:
    #  - "/dev/teensy:/dev/Teensy"
    #  - "/dev/imu_usb:/dev/Imu"
    #  - "/dev/lidar:/dev/Lidar"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # ubuntu24
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw # ubuntu22
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
    privileged: true
    # stdin_open: true  # Abychom udrželi interaktivní terminál
    tty: true  # Aby byl kontejner interaktivní
    # command: ros2 launch sim sim_launch.py
    #ports:
    # - 1883:1883
    command: /bin/bash -c "source /opt/ros/jazzy/setup.bash && source /home/ubuntu/ros_ws/install/setup.bash && rviz2"
  bridge:
    build:
      context: .  # Changed from ./bridge/ - Sets context to project root
      dockerfile: ./bridge/Dockerfile # Path to Dockerfile relative to new context
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./bridge:/home/ubuntu/bridge  # Mounts the bridge app's source
      - ./cpplib:/home/ubuntu/cpplib_src # Changed from ../cpplib - Mounts cpplib from project root
    working_dir: /home/ubuntu/bridge
    privileged: true
    stdin_open: true  # Add this line
    tty: true         # Add this line
    command: /bin/bash
