services:
  ros2_vhc: # First instance of ros2
    build:
      context: ./ros/
      dockerfile: Dockerfile
    container_name: ros2_vhc # Custom name
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=12 # Or a unique ID if needed
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
    privileged: true
    tty: true
    command: /bin/bash 

  ros2_mec: # Second instance of ros2
    build:
      context: ./ros/
      dockerfile: Dockerfile
    container_name: ros2_mec # Custom name
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY} 
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=13 # Example: different domain ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src # Shares sources, or use different paths if needed
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
    privileged: true
    tty: true
    command: /bin/bash # Example: different command, or another rviz2 if display handles it

  bridge:
    build:
      context: .
      dockerfile: ./bridge/Dockerfile
    container_name: my_bridge_instance # Custom name
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./bridge:/home/ubuntu/bridge
      - ./cpplib:/home/ubuntu/cpplib_src
    working_dir: /home/ubuntu/bridge
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash