services:
  discovery_service_p2p:
    build:
      context: .
      dockerfile: ./bridge/Dockerfile
    container_name: discovery_service_p2p
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./bridge:/home/ubuntu/bridge
      - ./DiscoveryService:/home/ubuntu/DiscoveryService
      - ./cpplib:/home/ubuntu/cpplib_src
    working_dir: /home/ubuntu/DiscoveryService
    privileged: true
    stdin_open: true
    tty: true
    # Launch Discovery Service with the --p2p flag
    command: ["/bin/bash", "-c", "cd /home/ubuntu/DiscoveryService && chmod +x ./autostart.sh && ./autostart.sh --p2p"]
    networks:
      public_net:
          ipv4_address: 192.168.65.5

  ros2_vhc_p2p_ds:
    build:
      context: ./ros/
      dockerfile: Dockerfile
    container_name: ros2_vhc_p2p_ds
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=12
      - LAUNCH_FILE=p2p_loopback_vhc_launch.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
      - ./ros/src/ros_ws/launch:/home/ubuntu/ros_ws/launch
      - ./cpplib:/home/ubuntu/cpplib_src
    privileged: true
    tty: true
    command: ["/bin/bash","-c","chmod +x /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh && source /opt/ros/jazzy/setup.bash && bash /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh"] 
    networks:
      public_net:
          ipv4_address: 192.168.65.101
    depends_on:
      - discovery_service_p2p

  ros2_mec_p2p_ds:
    build:
      context: ./ros/
      dockerfile: Dockerfile
    container_name: ros2_mec_p2p_ds
    environment:
      - DISPLAY=${DISPLAY} 
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=13
      - LAUNCH_FILE=p2p_loopback_mec_launch.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros/src/ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros/src/ros_ws/lib:/home/ubuntu/ros_ws/lib
      - ./ros/src/ros_ws/rosbags:/home/ubuntu/ros_ws/rosbags
      - ./ros/src/ros_ws/launch:/home/ubuntu/ros_ws/launch
      - ./cpplib:/home/ubuntu/cpplib_src
    privileged: true
    tty: true
    command: ["/bin/bash","-c","chmod +x /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh && source /opt/ros/jazzy/setup.bash && bash /home/ubuntu/ros_ws/src/modular_gateway_sender/p2p_autostart.sh"]
    networks:
      public_net:
          ipv4_address: 192.168.65.102
    depends_on:
      - discovery_service_p2p

networks:
    public_net:
        driver: bridge
        name: offloading-test-net-p2p-ds
        ipam:
            config:
                - subnet: 192.168.65.0/24
