<?xml version="1.0"?>
<package format="3">
  <name>offloading_latency_test_loopback</name>
  <version>0.0.1</version>
  <description>A ROS 2 Python package for loopback latency testing of VHC-MEC offloading.</description>
  <maintainer email="user@example.com">Your Name</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>modular_gateway_sender</depend>
  <depend>launch_ros</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
