# vehicle position in meters
float64 pose_rob_x
float64 pose_rob_y
float64 pose_rob_phi

# lidar position in meters
float64 pose_lid_x
float64 pose_lid_y
float64 pose_lid_phi

# map origin position in meters
# float64 pose_map_origin_x
# float64 pose_map_origin_y
# float64 pose_map_origin_phi

# vehicle position in grid
int32 map_rob_x
int32 map_rob_y

# lidar position in grid
int32 map_lid_x
int32 map_lid_y

# map origin position in grid
int32 map_origin_x
int32 map_origin_y
